source 'https://rubygems.org'

gem 'rails', '4.2.5.2'

gem 'rails-api'

gem 'spring', :group => :development

gem 'mysql2'

gem 'rack-cors', :require => 'rack/cors'

gem 'carrierwave', '~> 0.10.0'

gem 'mini_magick', '~> 4.3'